### PR TITLE
Hostapd_manager.sh, sdr-tool.sh and  .stxAliases updates

### PR DESCRIPTION
**Pull request by peepsnet**
.stxAliases changes:
alias secure='hostapd_manager.sh -e'
alias open='hostapd_manager.sh -o'

***
HOSTAPD_MANAGER.SH changes:
Added the ability to secure your wifi again. This seems to be working for me again. 
WiFi management via hostapd_manager.sh
1) SSH into your Stratux
2) Get root (sudo su -)
3) Type "hostapd_manager.sh"
4) READ THE SCREEN
5) Use at your own risk...

Added 2 aliases to the .stxAliases for opening and securing your WiFI. 
1) SSH into your Stratux
2) Get root(sudo su -)
3) type "open" or "secure" (I believe it is obvious what does what)
4) READ THE SCREEN!!
5) DON'T COMPLAIN IF YOU DON'T KNOW THE PASSWORD! YOU SHOULD HAVE READ THE SCREEN!
6) Done...

I updated the WIKI to reflect these new changes. so... hurry up... LOL

Dev Note:
using the `-q` switch will silence any user prompts. This would allow someone to call the script from with-in the go code, like from a json call via the settings page... SO one could create 2 buttons... One for `Secure Network` and one for `Open Network`

`hostapd_manager.sh -q -e` would set the wifi to secure with the default passphrase `SquawkDirtyToMe!`

`hostapd_manager.sh -q -o` would set the wifi to open

***
SDR-TOOL.SH changes:
Stratux service will now restart if you exit the script before its complete.

### CODE REVIEW

**Comment by TimTaylorToo** [comment]
I am not a programmer, just a user, so this stuff is not easy for me.  I tried the hostapd_manager.sh -e "password" and could not get it to work.  Should it work now?

**Comment by peepsnet** [comment]
This is a pull request. While this PR is open the code is not incorporated yet. When this is closed it will be in the code once updated

**Comment by TimTaylorToo** [comment]
I'm not sure what any of that means.  I guess you are saying it's not currently possible to password protect my Stratux.  When it is, this thread will be closed.

**Comment by peepsnet** [comment]
Yea. 

https://yangsu.github.io/pull-request-tutorial/

**Comment by peepsnet** [comment]
For the record
https://github.com/cyoung/stratux/issues/613 has info about thithis pr

**Comment by cyoung** [comment]
Merged then merged into ahrs_dev:

http://updates.stratux.me/builds/update-stratux-v1.3b2-6e184a9ce7.sh

**Comment by TimTaylorToo** [comment]
That worked! Thanks so much.  I was not able to get it to work with -p and my own password, but it worked with -e and your password.  I was using 8 number keys, so maybe it didn't like that, IDK.  Anyway, your password works.  Thanks again.

**Pull request merged**
