### PR TITLE
Updated GPS initialization and parsing

### PR DESCRIPTION
**Pull request by AvSquirrel**
Multiple changes to GPS handling. 
- Configure GNSS and NMEA messages at cold startup
- Fixed byte-order bug on UART configuration
- Set UART bit rate to 38400 bps. (Prevents message drops at 9600 bps / 10Hz; more reliable than higher rates)
- Add validation of NMEA message checksums
- Add support for u-blox 'PUBX' NMEA messages to reduce bandwidth requirement and simplify future satellite constellation parsing
- Improved horizontal accuracy calculation
- Add vertical velocity and vertical accuracy; update UI 'GPS/AHRS' page
- Add satellites tracked and satellites seen; update UI 'Status' page

Changes tested on u-blox M8 (RY835AI UART) and u-blox 7 (VK-172 USB). Should be compatible with all u-blox 6, 7, and 8 series GPS.

### CODE REVIEW

**Comment by cyoung** [comment]
Lots of errors on the first two or three starts:

```
2015/12/28 06:17:53 Using /dev/ttyAMA0 for GPS
2015/12/28 06:17:53 GPS configuration complete
2015/12/28 06:17:54 GPS error. Invalid NMEA string: Invalid NMEA message
2015/12/28 06:17:54 GPS error. Invalid NMEA string: Checksum failed. Calculated 0X9F; expected 0X1F
2015/12/28 06:17:54 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB4; expected 0X34
2015/12/28 06:17:54 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB5; expected 0X35
2015/12/28 06:17:54 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB2; expected 0X32
2015/12/28 06:17:54 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB3; expected 0X33
2015/12/28 06:17:54 count == 0, doing cleanup if necessary...
2015/12/28 06:17:54 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB0; expected 0X30
2015/12/28 06:17:54 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XBF; expected 0X3F
2015/12/28 06:17:54 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB7; expected 0X37
2015/12/28 06:17:55 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB6; expected 0X36
2015/12/28 06:17:55 GPS error. Invalid NMEA string: Checksum failed. Calculated 0X9F; expected 0X1F
2015/12/28 06:17:55 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XA1; expected 0X21
2015/12/28 06:17:55 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB5; expected 0X35
2015/12/28 06:17:55 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB3; expected 0X33
2015/12/28 06:17:55 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XB2; expected 0X32
2015/12/28 06:17:55 count == 0, doing cleanup if necessary...
2015/12/28 06:17:55 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XBB; expected 0X3B
2015/12/28 06:17:55 GPS error. Invalid NMEA string: Invalid checksum
2015/12/28 06:17:55 GPS error. Invalid NMEA string: Checksum failed. Calculated 0XEB; expected 0X6B
```

It seems like they subsided after running it a few times? Something with the config?

**Comment by cyoung** [comment]
```
$G�GG�,073749.90,,,,,0,00,99.99,,,,,,*61
$�UB�,00,073749.90,4228.62405,N,08339.66695,W,239.599,NF,9466308,6693691,0.000,0.00,0.000,,99.99,99.99,99.99,0,0,0*34
```

Some messages coming through like this - checksum is OK but message is garbled.

**Comment by AvSquirrel** [comment]
Your checksums suggest a single bit error on the MSB, where a "0" is being flipped to "1". I saw something similar once during testing; the GPS log on that stat showed multiple single-bit errors on the NMEA messages (anonymized example below). 

The top row is what was received by the RPi; the bottom is what actually would have been sent. The extended ASCII characters in the top row (Â, Ø, Î, ×, Ä) are 0x80 offsets from the "correct" characters on the bottom row. 
```
$PUÂØ,00,052918.10,44nn.nnnnn,Î,093nn.nnnnn,×,258.000,Ä3,1.5,2.2,0.175,23.89,0.015,,1.03,1.51,1.05,10,0,0*78
$PUBX,00,052918.10,44nn.nnnnn,N,093nn.nnnnn,W,258.000,D3,1.5,2.2,0.175,23.89,0.015,,1.03,1.51,1.05,10,0,0*78
```
I'd guess that this could be a sync / timing error on the port; I reset the RPi bit rate from / to 38400 ```(stty -F /dev/ttyAMA0 9600; stty -F /dev/ttyAMA0 38400)``` and the problem cleared itself in real time. itself. It didn't come back on the next reset, and I haven't seen it since.

As far as a fix / prevention, a lower bit rate might help. The new code only needs about 12 kbps to feed messages at 10 Hz (including the 1 Hz status messages), so I don't see any reason this couldn't be dropped down to 19.2 kbps.

**Comment by cyoung** [comment]
Turned off AHRS and it cleared up after restarting gen_gdl90, not sure if coincidence or not.

**Comment by cyoung** [comment]
gps

**Comment by AvSquirrel** [comment]
Try https://github.com/AvSquirrel/stratux/commit/48f3170df9190b168f00bba2f14d07c15ca5391e .

This adds a 250 ms delay after GPS initialization completes, before the port is reopened at 38.4k.

I noticed at the beginning of the GPS logs that I was picking up the ACKs from UBX configuration messages. Could be that the GPS is slower than the RPi to respond. This should give the GPS a chance to "settle in" before reading at the higher rate.

**Pull request merged**
