### PR TITLE
Sqlite logging.

### PR DESCRIPTION
**Pull request by cyoung**
* Improved buffering.
* Batched queries.
* Only log sentences for which `processNMEALine()` returns true by default unless `globalSettings.DEBUG` is true.
* Traffic logging.

### CODE REVIEW

**Comment by AvSquirrel** [comment]
- Hardware: Pi2, RY835AI, 1 x RTL-SDR blog receiver. 
- Software: 2d10744 built from source.
- Config: 1090 MHz and GPS enabled. 978 MHz and AHRS disabled. 

Seeing some oddball behaviors with the new sqlite code:
1. gen_gdl90 doesn't always quit on SIGTERM. E.g. run from command line, hit ctrl-C. The shutdown sequence starts (ES shutdown is called) but never finishes. Seen with Traffic Markings and Replay Logs disabled or enabled.
2. Even with Replay Logs enabled and clean shutdowns of gen_gdl90, I don't always see updated data in the sqlite file after any given run.
3. During one run, I got a panic for a null pointer reference to [dataLogTimestamps](https://github.com/cyoung/stratux/blob/master/main/datalog.go#L75). Here's the partial stack trace.

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1a0 pc=0xd7a74]

goroutine 29 [running]:
main.checkTimestamp(0x108cbedc)
        /root/stratux/main/datalog.go:75 +0x238
main.dataLog()
        /root/stratux/main/datalog.go:403 +0x64c
created by main.initDataLog
        /root/stratux/main/datalog.go:467 +0xb4

goroutine 1 [select (no cases), 3 minutes]:
main.main()
        /root/stratux/main/gen_gdl90.go:1293 +0xdbc

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
        /root/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 20 [syscall, 3 minutes]:
os/signal.loop()
        /root/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /root/go/src/os/signal/signal_unix.go:28 +0x30
````

**Comment by skypuppy** [comment]
Does golang have a flush() or fflush() routine?  Just a SWAG.

**Comment by AvSquirrel** [comment]
Hmm. GPS and traffic just stopped updating, but gen_gdl90 continues to run. `cat /dev/ttyAMA0` shows that the Pi's still getting valid messages from the GPS.

image

````
2016/04/02 16:23:55 ==================================================================
2016/04/02 16:23:55 A4943E => {"Icao_addr":10785854,"Tail":"","Emitter_category":0,"OnGround":false,"Addr_type":0,"TargetType":0,"SignalLevel":-31.7979854051436,"Position_valid":false,"Lat":0,"Lng":0,"Alt":32975,"GnssDiffFromBaroAlt":0,"AltIsGNSS":false,"NIC":0,"NACp":0,"Track":0,"Speed":0,"Speed_valid":false,"Vvel":0,"Timestamp":"2016-04-02T16:22:58.678Z","Age":56.05,"Last_seen":"0001-01-01T00:21:17.95Z","Last_alt":"0001-01-01T00:21:17.95Z","Last_GnssDiff":"0001-01-01T00:00:00Z","Last_GnssDiffAlt":0,"Last_speed":"0001-01-01T00:00:00Z","Last_source":1,"ExtrapolatedPosition":false,"Bearing":0,"Distance":0}
2016/04/02 16:23:55 406B13 => {"Icao_addr":4221715,"Tail":"eTOM032","Emitter_category":5,"OnGround":false,"Addr_type":0,"TargetType":1,"SignalLevel":-17.1536626683541,"Position_valid":true,"Lat":45.285503,"Lng":-93.27747,"Alt":39975,"GnssDiffFromBaroAlt":-900,"AltIsGNSS":false,"NIC":8,"NACp":9,"Track":206,"Speed":526,"Speed_valid":true,"Vvel":64,"Timestamp":"2016-04-02T16:23:09.075Z","Age":45.9,"Last_seen":"0001-01-01T00:21:28.1Z","Last_alt":"0001-01-01T00:21:28.25Z","Last_GnssDiff":"0001-01-01T00:21:28.1Z","Last_GnssDiffAlt":39975,"Last_speed":"0001-01-01T00:21:28.1Z","Last_source":1,"ExtrapolatedPosition":false,"Bearing":0,"Distance":0}
2016/04/02 16:23:55 AD4171 => {"Icao_addr":11354481,"Tail":"","Emitter_category":5,"OnGround":false,"Addr_type":0,"TargetType":0,"SignalLevel":-26.540384581868587,"Position_valid":false,"Lat":0,"Lng":0,"Alt":5525,"GnssDiffFromBaroAlt":0,"AltIsGNSS":false,"NIC":0,"NACp":0,"Track":0,"Speed":0,"Speed_valid":false,"Vvel":0,"Timestamp":"2016-04-02T16:23:08.967Z","Age":57.8,"Last_seen":"0001-01-01T00:21:16.2Z","Last_alt":"0001-01-01T00:21:28.25Z","Last_GnssDiff":"0001-01-01T00:00:00Z","Last_GnssDiffAlt":0,"Last_speed":"0001-01-01T00:00:00Z","Last_source":1,"ExtrapolatedPosition":false,"Bearing":0,"Distance":0}
2016/04/02 16:23:55 On  192.168.10.13:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:23:55 On  192.168.10.13:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:23:55 On  192.168.10.11:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:23:55 On  192.168.10.11:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:23:55 On  192.168.10.10:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:23:55 On  192.168.10.10:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:23:55 On  192.168.10.12:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:23:55 On  192.168.10.12:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:23:55 8466C7 => {"Icao_addr":8677063,"Tail":"eNCA132","Emitter_category":5,"OnGround":false,"Addr_type":0,"TargetType":1,"SignalLevel":-20.4875964967566,"Position_valid":true,"Lat":44.925385,"Lng":-94.17709,"Alt":34975,"GnssDiffFromBaroAlt":-825,"AltIsGNSS":false,"NIC":8,"NACp":9,"Track":132,"Speed":573,"Speed_valid":true,"Vvel":-64,"Timestamp":"2016-04-02T16:23:09.129Z","Age":45.6,"Last_seen":"0001-01-01T00:21:28.4Z","Last_alt":"0001-01-01T00:21:28.4Z","Last_GnssDiff":"0001-01-01T00:21:28.05Z","Last_GnssDiffAlt":34975,"Last_speed":"0001-01-01T00:21:28.05Z","Last_source":1,"ExtrapolatedPosition":false,"Bearing":0,"Distance":0}
2016/04/02 16:23:55 A7A08A => {"Icao_addr":10985610,"Tail":"eUAL160","Emitter_category":0,"OnGround":false,"Addr_type":0,"TargetType":1,"SignalLevel":-17.55920893327612,"Position_valid":true,"Lat":45.086773,"Lng":-93.381645,"Alt":34000,"GnssDiffFromBaroAlt":0,"AltIsGNSS":false,"NIC":0,"NACp":0,"Track":193,"Speed":554,"Speed_valid":true,"Vvel":0,"Timestamp":"2016-04-02T16:23:09.082Z","Age":45.9,"Last_seen":"0001-01-01T00:21:28.1Z","Last_alt":"0001-01-01T00:21:28.35Z","Last_GnssDiff":"0001-01-01T00:00:00Z","Last_GnssDiffAlt":0,"Last_speed":"0001-01-01T00:21:28Z","Last_source":1,"ExtrapolatedPosition":false,"Bearing":0,"Distance":0}
2016/04/02 16:23:56 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/04/02 16:24:01 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/04/02 16:24:06 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/04/02 16:24:10 List of all aircraft being tracked:
2016/04/02 16:24:10 ==================================================================
2016/04/02 16:24:10 On  192.168.10.11:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:24:10 On  192.168.10.10:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:24:10 On  192.168.10.10:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:24:10 On  192.168.10.12:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:24:10 On  192.168.10.12:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:24:10 On  192.168.10.13:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:24:10 On  192.168.10.13:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:24:10 On  192.168.10.11:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:24:11 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/04/02 16:24:16 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/04/02 16:24:21 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/04/02 16:24:25 List of all aircraft being tracked:
````

**Comment by AvSquirrel** [comment]
.... and it just came back alive after 22 minutes.

image

````
2016/04/02 16:45:57 On  192.168.10.13:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:45:57 On  192.168.10.11:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:45:57 On  192.168.10.11:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:45:57 ==================================================================
2016/04/02 16:45:57 On  192.168.10.10:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:45:57 On  192.168.10.10:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:45:57 On  192.168.10.12:4000,  Queue length = 0 messages / 0 bytes
2016/04/02 16:45:57 On  192.168.10.12:49002,  Queue length = 0 messages / 0 bytes
2016/04/02 16:45:58 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/04/02 16:46:03 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/04/02 16:46:06 stats [started: 44 minutes ago]
2016/04/02 16:46:06  - CPUTemp=37.39 deg C, MemStats.Alloc=20 MB, MemStats.Sys=69 MB, totalNetworkMessagesSent=2,795
2016/04/02 16:46:06  - UAT/min 0/0 [maxSS=0.00%], ES/min 0/4,731
, Total traffic targets tracked=28
2016/04/02 16:46:06  - Network data messages sent: 663 total, 663 nonqueueable.  Network data bytes sent: 11057 total, 11057 nonqueueable.
2016/04/02 16:46:06  - Last GPS fix: 22 minutes ago, GPS solution type: 0 using 0 satellites (0/0 seen/tracked), NACp: 10, est accuracy 8.20 m
2016/04/02 16:46:06  - GPS vertical velocity: 0.13 ft/sec; GPS vertical accuracy: 9.8 m
2016/04/02 16:46:07 Exiting gpsSerialReader() after i=4365 loops
2016/04/02 16:46:08 Average sendable queue is 0 messages. Changing queue timer to 0.100000 seconds
2016/04/02 16:46:08 Using /dev/ttyAMA0 for GPS
2016/04/02 16:46:08 Finished writing u-blox GPS config to /dev/ttyAMA0. Opening port to test connection.
2016/04/02 16:46:10 List of all aircraft being tracked:
2016/04/02 16:46:10 ==================================================================
2016/04/02 16:46:10 A7A08A => {"Icao_addr":10985610,"Tail":"eUAL160","Emitter_category":0,"OnGround":false,"Addr_type":0,"TargetType":1,"SignalLevel":-29.154237220656686,"Position_valid":true,"Lat":44.847218,"Lng":-93.4493,"Alt":34000,"GnssDiffFromBaroAlt":0,"AltIsGNSS":false,"NIC":0,"NACp":0,"Track":191,"Speed":556,"Speed_valid":true,"Vvel":0,"Timestamp":"2016-04-02T16:24:44.362Z","Age":0.1,"Last_seen":"0001-01-01T00:44:30Z","Last_alt":"0001-01-01T00:44:30Z","Last_GnssDiff":"0001-01-01T00:00:00Z","Last_GnssDiffAlt":0,"Last_speed":"0001-01-01T00:44:30Z","Last_source":1,"ExtrapolatedPosition":false,"Bearing":0,"Distance":0}
````

**Pull request merged**
