### PR TITLE
Website: Add height above ellipsoid

### PR DESCRIPTION
**Pull request by PepperJo**
Add GPS height above WGS-84 ellispoid to the website.

Signed-off-by: PepperJo <pepperjo@japf.ch>

### CODE REVIEW

**Comment by PepperJo** [comment]
ping

**Comment by PepperJo** [comment]
I'm fine with closing this if there is no interest in showing GPS height WGS-84.

**Comment by acasadoalonso** [comment]
Jonás
It is important for the Flarm
There we need the altitude over the geoide 

Enviado desde mi iPhone.
AC/.

**Comment by PepperJo** [comment]
Agree but this pull request is only for *displaying* height over geoide. Conversion code can be found in another pull request: https://github.com/cyoung/stratux/pull/755

**Comment by Christian-neu** [comment]
Hello 
TOP
but Serial in     "is not  ;o( "

**Comment by cyoung** [comment]
Looks good, thanks for submitting.

**Pull request merged**
