### PR TITLE
show which types of uat messages we've gotten

### PR DESCRIPTION
**Pull request by haykinson**
known issue with this still: not resetting to zero after a product is no longer sent by the server.

### CODE REVIEW

**Comment by bradanlane** [comment]
Interesting addition. One thing this code will introduce is a mis-alignment with the responsive layout is side-by-side.

As new content appears in the webUI, that layout is becoming stressed.

The webUI needs to grow beyond its one "status" screen.

The UAT details look like another good example of "details" which need to have a secondary screen. Another example of "details" in development is Log Messages. All "details" should have a consist UX.

I don't know what the right UX is at the moment which is why the Log Messages are not exposed yet. I'll keep the UAT strings in mind when I do the design.

**Comment by haykinson** [comment]
@bradanlane perhaps just inner tabs? this way each aspect gets a tab sheet of its own to play in, and can call the server only when on that sheet?

**Comment by cyoung** [comment]
Good addition, thank you!


"known issue with this still: not resetting to zero after a product is no longer sent by the server."
Can you elaborate on this?

**Comment by cyoung** [comment]
Check extract_metar.go:decodeUplink(), getting an accurate count on this requires that we start parsing the uplink packet in that way. One uplink message will, for example, contain multiple METARs.

**Comment by haykinson** [comment]
@cyoung re not resetting to zero, the UI doesn't clear rows without data, which means it forever sticks around at the last value received. I'll fix that in a separate PR.

Re decoding uplink messages, yes, I think we could get much more sophisticated. I'm not sure that's as important as getting some rough insight into what's being received but I'll look at it at some point.

**Pull request merged**
