### PR TITLE
spindle: add edimax hostapd src and build

### PR DESCRIPTION
**Pull request by jpoirier**
Not sure if you're interested in this but figured I'd PR it anyway. If not, just close the PR.

### CODE REVIEW

**Comment by cyoung** [comment]
So this is a newer version than that binary?

**Comment by jpoirier** [comment]
Btw, I'll add the build commands to circle ci only if you accept the merge.

**Comment by cyoung** [comment]
Hrm, and the source of wpa_supplicant_hostapd.tgz?

**Comment by jpoirier** [comment]
@cyoung It's the source code that builds the hostapd binary you're using now. The latest hostapd source code from edimax is dated 2012.

**Comment by cyoung** [comment]
https://github.com/jenssegers/RTL8188-hostapd ?

**Comment by jpoirier** [comment]
No, it's the original source from here http://www.edimax.com/images/Image/Driver_Utility/Wireless/NIC/EW-7811Un/EW-7811Un_Linux_driver_v1.0.0.5.zip

**Comment by jpoirier** [comment]
Via that download link from the edimax website, if you dig down it's tagged as wpa_supplicant_hostapd-0.8_rtw_r7475.20130812.tar.gz

**Comment by Ergonomicmike** [comment]
My 2¢: Since some in the Stratux Project (and some outside the Project) have reported problems with BLOD and/or disconnects, we should consider rolling our own hostapd. It's true that the driver is ancient. But the kernel has moved on. I don't know what compiling anew brings to the table. You all do. Is a fresh compile a plus? (OTOH, maybe there's something hacky in that ancient driver that squeaks by on an old kernel? Although I've been running for 36 hours w/o problems. (Albeit at home.)) If it seems like this could mitigate thr BLOD issue, we might want to try it for a while, at least in alpha.

**Comment by cyoung** [comment]
If you have success with it, Mike, we'll go ahead with it. You've had more BLOD issues than anyone.

**Comment by skypuppy** [comment]
Mike, have you ever seen the Grand Canyon?  Or a detailed mapping of 
brain synapses (within practical limits?)

Well, all the twists and turns you see visually in either of the above 
examples is a good analogy to kernel/driver software issues. Old kernels 
that work with old drivers don't work with new kernels and re-compiled 
drivers.  So many things are so interdependent that it truly takes a 
specialist (or twenty) on THAT piece of hardware along with THAT driver 
source code for THAT kernel.  It really is that complex.
The genius programmers/kernel hackers write such that things are generic 
enough but still powerful enough that *most* reconfigured drivers can work.
It really is not easy.
The Winblows people never did figure that out, but then, they have 
literally thousands of driver writers trying to make drivers for a very 
closed operating system (ha!) so it truly is a wonder that anything 
works in that environment.

I used to write in assembly/machine language with just a limited set of 
hardware out there and the OS had at least a minimal set of docs that 
you could write to (sometimes it was wrong, too.) <sigh>

Now that C is so ubiquitous for writing drivers and libraries, the world 
is a nicer place.  Yeah, C has it's limits, as does every single tool 
that man has ever made and software is comprised of *the* single most 
complex tools we have ever devised.

Stratux is one fine example.

So writing a new driver for librtlsdr (and with no compensation) would 
truly be a labor of love and would probably take a great deal of time.

Skypuppy

**Comment by jpoirier** [comment]
On Thu, Mar 10, 2016 at 5:59 PM, skypuppy <notifications@github.com> wrote:

> So writing a new driver for librtlsdr (and with no compensation) would
> truly be a labor of love and would probably take a great deal of time.
>
> Skypuppy


Scratching head...

Are you sure you're commenting on the thread you think you're commenting on
because the topic of this thread is "should we build the hostapd binary
from source or continue to use the pre-built binary we've been using"

**Comment by skypuppy** [comment]
Joseph, Mike mentioned *writing* a new one.

**Comment by jpoirier** [comment]
On Thu, Mar 10, 2016 at 6:29 PM, skypuppy <notifications@github.com> wrote:

> Joseph, Mike mentioned *writing* a new one


 As far as I can tell, you're the first to mention librtlsdr in this thread.

**Comment by skypuppy** [comment]
Yeah, I said librtlstr when imeant hostapd.  I have librtlsdr on the 
brain because I have been working on that so hard.  :)  Brain fart. 
Sorry, guys.

**Comment by jpoirier** [comment]
On Thu, Mar 10, 2016 at 6:35 PM, skypuppy <notifications@github.com> wrote:

> Yeah, I said librtlstr when imeant hostapd. I have librtlsdr on the
> brain because I have been working on that so hard. :) Brain fart.
> Sorry, guys.


Figured maybe s/librtlsdr/hostapd

But we're not re-writing hostapd, the proposal is to use the latest edimax
hostapd source code, which we have, to compile the hostapd *executable* and
use it instead of the pre-built binary we currently use, which is dated
2012ish.

What are you doing with librtlsdr?

**Comment by skypuppy** [comment]
caution: possible thread hijack

Trying to recompile everything for jessie (and then RPi3 if I ever get 
one.)  :)
The rtlsdr library was worked on over a week on the pi with no success, 
so i loaded source from here and there and cross-compiled from Linux 
jessie on a PC, using Qt.  Had success so on to the next module.  Been 
too busy to work on any more this last 7 days.

Also porting the BNO055 and Adafruit Ultimate GPS to stratux in jessie 
for the pi.  Could take months.

Skypuppy

**Comment by jpoirier** [comment]
fyi - been running a compiled hostapd binary with stratux (latest tip) on an RPi2 loaded with Jessie for nearly twenty hours now with no hiccups. On a side note, it's kinda nice to be able to open the web ui and log files on the same system that stratux is running on.

**Comment by Ergonomicmike** [comment]
4 days on the compiled hostapd (wheezy + rpi-update), no problems. (With clients on and off.) But again, I never have BLOD's at home. Next flight Tuesday.

**Comment by cyoung** [comment]
@Ergonomicmike - how did your flight today go with hostapd compiled from above source?

**Comment by jpoirier** [comment]
PR #335

**Pull request closed without merging**
