### PR TITLE
BNO055 driver and partial web interface integration.

### PR DESCRIPTION
**Pull request by tino-247**
Added BNO055 support and partial web interface integration.
Debug is on by default so this should only be used for testing.

### CODE REVIEW

**Comment by cyoung** [comment]
@tino-247 - thanks for submitting. Do you have any demo video on this? I don't have a BNO055 to try it out yet.

**Comment by tino-247** [comment]
I made a quick screen record from my phone:
http://s000.tinyupload.com/?file_id=04539856573015197387

**Comment by andofrjando** [comment]
#407 
I've connected the BNO055 to the GPIO UART pins on the raspberry pi and have it connected to Stratux by changing making changes [here in AHRS.go](https://github.com/tino-247/stratux/blob/57dc241f99f0d95a1a4a6d337bde0fde748f2c55/main/AHRS.go#L901-L904) to use /dev/ttyAMA0 (as well as the necessary changes to disable the kernel serial port). My Stratux web interface shows changes to the orientation of BNO055 just as in the video above. 
I can't get this to work with my Electronic Flight Bag though (I use Avplan). The EFB just says 'No AHRS data'. I'm not sure if the problem is with the electronic flight bag or if it has to with the GDL90 message. Does any one have any suggestions for another app to test AHRS functionality? As an aside, the [link in AHRS.go](https://github.com/tino-247/stratux/blob/57dc241f99f0d95a1a4a6d337bde0fde748f2c55/main/gen_gdl90.go#L38) for the GDL90 spec gives a 404 now. Don't suppose anyone has a copy?

**Comment by tino-247** [comment]
https://github.com/tino-247/stratux/tree/57dc241f99f0d95a1a4a6d337bde0fde748f2c55/notes

**Comment by cyoung** [comment]
Merging to aid in testing, I don't have the hardware yet and not able to test.

If anyone has a BNO055 to test with, here's an update file to use (make sure to unzip it first):


[update-stratux-v1.0r1-9b83f65768.sh.zip](https://github.com/cyoung/stratux/files/646369/update-stratux-v1.0r1-9b83f65768.sh.zip)

**Pull request merged**
