### PR TITLE
add OwnshipModeS to UI; tweaked Settings field validation

### PR DESCRIPTION
**Pull request by bradanlane**
The OwnShipModeS value is assumed to come in as string (HEX) but goes back out as an integer, this really messes with the normal processing of configuration settings. Since teh HEX string is eas yfor users to enter in the UI, it made sense to preserve that in the UI and in the stratux.conf file. Therefore, it becomes necessary to work wit hthe HEX string in the Go code.

I was able to test all of the GO code with the exception of the makeOwnshipReport();

There was an issue when attempting to clear the WeatherList. It would not allow the list to be reset back to 'blank'. I updated the validation code to handle this. I also now detect field focus changes to trigger validation and storage rather than just triggering from the 'form submit' event.

### CODE REVIEW

**Comment by bradanlane** [comment]
I was not sure exactly how that code worked. The problem from the end user point of view is they can find a HEX or an OCT representation of their ModeS code. Thus, the UI needs to deal with that. Consequently, the UI interfaces with the stratux.conf file so it too needs to be either HEX or OCT.

**Comment by cyoung** [comment]
Are you validating the hex/oct format and/or length in the iface?

**Comment by bradanlane** [comment]
not currently. the HEX code is validated in handleSettingsSetRequest()

**Comment by bradanlane** [comment]
I'll wait to work on any more UI until you can resolve this pull request.

**Comment by cyoung** [comment]
On second thought, it all looks pretty good - was just a little bit unfamiliar with the way you were doing it. No changes needed.

**Pull request merged**
