### PR TITLE
minor tweaks

### PR DESCRIPTION
**Pull request by jpoirier**

### CODE REVIEW

**Comment by Ergonomicmike** [comment]
Okay. Tnx.

**Comment by jpoirier** [comment]
@Ergonomicmike 

I have a stratux-setup bash script I just hacked together if you want to give it a try? 

It's mostly what's in image/spindle/wheezy-stage4 but with some mods/tweaks. Theoretically, you should be able to setup stratux on a stock RPi2 (and possibly an RPi3) OS without the need to use the release image. I've not had a chance to test it yet, probably get to it Monday evening.

**Comment by skypuppy** [comment]
I'd like to experiment with that, too, Joseph, if you're willing.

**Comment by jpoirier** [comment]
is skypuppy your reddit user name

**Comment by skypuppy** [comment]
skypuppy7 over there (it would not let me have skypuppy)

**Comment by skypuppy** [comment]
Is that a good thing or a bad thing?  :)

**Pull request merged**
