### PR TITLE
improvements for mobile device support of the webUI

### PR DESCRIPTION
**Pull request by bradanlane**
made layout responsive to mobile devices
formatted uptime (this would be better done in the socket code)
added mobile web app icon
added prompt to pin webUI to device homescreen
added shape formatting to red/green indicators for accessibility
updated styles to reflect current design recomendations

suggestion for socket data - add RPi board temperature
/sys/class/thermal/thermal_zone0/temp

### CODE REVIEW

**Comment by cyoung** [comment]
Excellent! Good suggestion on the RPi board temperature.

**Comment by cyoung** [comment]
https://github.com/cyoung/stratux/commit/ecd29a8425c5bb8b1088a65d9df6ccd6f50444c2

**Comment by cyoung** [comment]
Getting:

     TypeError: time_parts is null

And "Uptime: --". Just after starting.

**Comment by bradanlane** [comment]
Ok. Let me check that. I was getting the error on the local uptime temporary variable but there must be a condition when uptime is defined but the value is unrecognized.

**Comment by BrantKyser** [comment]
What about formatting the uptime on the server side. It looks like Go provides a way to represent time in about any conceivable format.

**Comment by cyoung** [comment]
Sure, how do we want it formatted?

**Comment by bradanlane** [comment]
Actually I was about to suggest the opposite. Separate data from formatting. Keep the format in the JS code

**Comment by cyoung** [comment]
Well, let's do that then. Ball is in your court :)

Here is a string that breaks the current display: "Uptime":"7.004683139s"

**Comment by bradanlane** [comment]
That sting would indeed break my code. Sorry about that. Working on the code now.

**Comment by bradanlane** [comment]
This will take a little while. I'm going to need to build a Dev environment

**Pull request merged**
