### PR TITLE
Use ReplayLog data to create KML files of both traffic and ownship

### PR DESCRIPTION
**Pull request by alexberryman**
Changes to the Settings page allows the user to dump the ReplayLog (traffic+ownship) SQLite file or in the new "GPS Track File" panel to just dump the ownship  `mySituation` GPS data. The new 'Write GPS to file' setting only writes the `mySituation` portion of ReplayLog to limit the growth of the stratux.sqlite file size.

The ReplayLog KML file can be created with animations based on time, or altitude. The altitude filter is useful to remove cruise traffic and view traffic below. Demo: https://zippy.gfycat.com/OfficialFirstChinesecrocodilelizard.webm

The KML files have folders based on the following criteria:
- ownship
- ADS-B Traffic w/min alt < FL180
- ADS-B Traffic w/min alt > FL180
- UAT Traffic (`TARGET_TYPE>1`)

Clicking on traffic trails will display minimum and maximum altitude and provide links to Flightaware.

The only thing I think I am missing is a way to clear the SQLite file from the web UI to either free up space or when starting a new flight.

### CODE REVIEW

**Comment by peepsnet** [comment]
WOW! Nice

**Comment by cyoung** [comment]
Looks pretty good. The biggest issue I have with this is that it opens and runs from the gen_gdl90 daemon. File locking issues.

Breaking out some of the replay log features is a good idea.

How are most people handling .kml files?

**Comment by Bearcode** [comment]
Does the [Write-Ahead Logging](https://sqlite.org/wal.html) in SQLite3 prevent the file lock issues you are concerned with? In my testing I haven't been able to create a file lock error. It looks like there is no issue with concurrent writes from `datalog.go` and reads from `export-datalog.go`.

Here is a [Gist of lsof output](https://gist.github.com/Bearcode/932a0f4f6c1e2a309b5e80ec53543f88) showing multiple locks on the SQLite, `-wal` and `-shm` files while testing concurrent reads and writes.

Is there any part of the code base that doesn't run under gen_gdl90 that I can look at as an example for breaking out these functions?

**Comment by evannadeau** [comment]
Any chance there can be future movement on this?  How about saving the files to another partition on the microSD?  I have a 32GB one that I put Stratux on.  It is still however only using the standard 2GB partition.  Another 28GB (after formatting) still kicking around I'm sure.

**Comment by alexberryman** [comment]
Stale PR

**Comment by benlawraus** [comment]
Hi, can the work of @alexberryman be merged please ?  In developer mode maybe?  This would make stratux the only adsb device with flight logging....

**Pull request closed without merging**
