### PR TITLE
sdr: fix 1090 shutdown hang, add shutdown completed messages

### PR DESCRIPTION
**Pull request by jpoirier**
fixes issue #323 and issue #324

### CODE REVIEW

**Comment by jpoirier** [comment]
@AvSquirrel  @cyoung 

I created a dump1090 PR that corrects several stderr to stdout and once it's merge I'll update the todo listed in the sdr.go of this PR  

https://github.com/AvSquirrel/dump1090/pull/1

**Comment by jpoirier** [comment]
@AvSquirrel @cyoung 

fyi - implemented a cleaner solution for handling premature process exit so not dump1090 stderr/stdout changes required

**Comment by zendor** [comment]
@jpoirier 
I'm still noticing an issue where dump1090 is not getting killed.

To reproduce: configuration is 1 SDR
start with both 978MHz and 1090MHz disabled in globalSettings
1. settings -> enable 1090MHz
2. settings -> enable 978MHz
978MHz should disable 1090MHz and I see the following in the logs:
wrote settings.
Entered ES shutdown() ...
ES shutdown(): calling e.wg.Wait() ...

but the kill signal is never sent and dump1090 remains running

**Comment by jpoirier** [comment]
@zendor are you using the code in this PR?

**Comment by zendor** [comment]
yes I'm using the latest pull request code.  Here's a copy of the commands run on my raspi:
git remote add jp https://github.com/jpoirier/stratux.git
git fetch jp
git pull jp dump1090_fix

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 6:23 PM, zendor <notifications@github.com> wrote:

> yes I'm using the latest pull request code. Here's a copy of the commands
> run on my raspi:
> git remote add jp https://github.com/jpoirier/stratux.git
> git fetch jp
> git pull jp dump1090_fix
>
Okay, thanks for testing it. I'd tested the initial commit, without the
additional groutine, and it seemed to work, let me see what I can figure
out.

**Comment by jpoirier** [comment]
@zendor I just tested it and it's working for all scenarios as expected.

This is how I fetch the PR from within the cyoung/stratux repo folder

    git fetch origin pull/236/head:dump1090_fix 

I've been commenting out the following line in the Makefile as well

    #go get -t -d -v ./main ./test ./linux-mpu9150/mpu ./godump978 ./mpu6050 ./uatparse

then run:

    make all
    make install
    gen_gdl90

**Comment by zendor** [comment]
Hey @jpoirier thanks for looking into it.  I've been compiling some debug code and I'm running further tests right now.  I think that in the failure scenario I see the code never reaches scanStderr.scan() in the loop that would issue the kill command.
```
if scanStdout.Scan() {
        replayLog(scanStdout.Text(), MSGCLASS_DUMP1090)
}
if err := scanStdout.Err(); err != nil {
        log.Printf("scanStdout error: %s\n", err)
}

log.Println("about to execute Scan stderr") // never reaches here
if scanStderr.Scan() {
```

I'm still debugging

**Comment by zendor** [comment]
I'm actually not terribly familiar with golang and I was wondering if the scanStdout.Scan() call is a blocking call? If so, would that mean that dump1090 wouldn't shut down unless a byte is received?

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 7:12 PM, zendor <notifications@github.com> wrote:

> I'm actually not terribly familiar with golang and I was wondering if the
> scanStdout.Scan() call is a blocking call? If so, would that mean that
> dump1090 wouldn't shut down unless a byte is received?
>

It returns if there is nothing to read. There was a problem when it was
"for scanStdout.Scan() {" due to the amount of stdout messages that were
coming from dump1090t but changing the "for" to "if" helped.

I just noticed that after letting it run for a while then disabling 1090
via the web ui causes it to not cleanly shutdown anymore. So I'm guessing
there's still something going on with the scan methods.

**Comment by zendor** [comment]
I found the source for the Scan function in bufio:
https://golang.org/src/bufio/scan.go?s=5433:5462#L133

I'm not 100% certain that the scan call doesn't block but in any case I'll submit a pull request with a modified sdr.go in which I've split the closing thread from the reading thread.  This appears to eliminate all dump1090 shutdown hangs.

Thanks for the quick replies!

**Comment by zendor** [comment]
With the latest edit (change to standard read methods) I still see the shutdown hang. I'm using go version go1.5.2 linux/arm.

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 8:44 PM, zendor <notifications@github.com> wrote:

> With the latest edit (change to standard read methods) I still see the
> shutdown hang. I'm using go version go1.5.2 linux/arm.
>
Just an intermediate push to get rid of the scanner, that particular Read
does block and I'm making changes still.

**Comment by zendor** [comment]
Ah ok, thanks :)

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 8:47 PM, Joseph Poirier <jdpoirier@gmail.com> wrote:

> On Sat, Mar 12, 2016 at 8:44 PM, zendor <notifications@github.com> wrote:
>
>> With the latest edit (change to standard read methods) I still see the
>> shutdown hang. I'm using go version go1.5.2 linux/arm.
>>
> Just an intermediate push to get rid of the scanner, that particular Read
> does block and I'm making changes still.
>

Maybe we'll go back to scanner and I'll merge your change.

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 8:50 PM, zendor <notifications@github.com> wrote:

> Ah ok, thanks :)
>
Thanks for the PR! This has been a bit of a PITA.

**Comment by zendor** [comment]
Haha, no problem! Thanks for helping out on the stratux project! :-D

**Comment by Ergonomicmike** [comment]
@jpoirier Thanks for the install instructions above. Just before going for a flight today I copied your 2nd version of sdr.go into my SD card and tried the usual make, but it didn't work. I ended up flying with v0.8r1, 4.1.9 kernel and my compiled hostapd. Only a two hour test, but no BLODs. (I'll just wait for the .sh's to catch up to development - too bleeding edge for me. <grinning>)

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 11:07 PM, Ergonomicmike <notifications@github.com>
wrote:

> @jpoirier <https://github.com/jpoirier> Thanks for the install
> instructions above. Just before going for a flight today I copied your 2nd
> version of sdr.go into my SD card and tried the usual make, but it didn't
> work.
>
Sorry. I'm guessing you caught a commit that had errors in the sdr.go file,
which is my fault entirely for abusing github and the PR mechanism as
intermediate storage between my dev laptop and the RPi2.

**Comment by Ergonomicmike** [comment]
@jpoirier No harm, no foul. I'm happy you're squashing bugs and thought it would be good to fly with one less dump_1090 running.

**Comment by AvSquirrel** [comment]
336d17d seems to be working cleanly on my development branch (now 40+ commits ahead of cyoung master). UI changes and physical disconnects / reconnects both cause dump1090 to unload or reload as appropriate.

One observation -- and I'd like you confirm that this is intentional -- is that any state changes (SDR enabled / disabled; SDR plugged in or removed) cause both readers to be torn down, then set up again in the desired configuration.

**Comment by jpoirier** [comment]
On Sun, Mar 13, 2016 at 9:02 PM, AvSquirrel <notifications@github.com>
wrote:

> 336d17d
> <https://github.com/cyoung/stratux/commit/336d17d615efd7f6e80f7e5752f78e354d84fcba>
> seems to be working cleanly on my development branch (now 40+ commits ahead
> of cyoung master). UI changes and physical disconnects / reconnects both
> cause dump1090 to unload or reload as appropriate.
>
> One observation -- and I'd like you confirm that this is intentional -- is
> that any state changes (SDR enabled / disabled; SDR plugged in or removed)
> cause both readers to be torn down, then set up again in the desired
> configuration.
>
Yes, that's by design.

**Comment by jpoirier** [comment]
On Sun, Mar 13, 2016 at 9:15 PM, Joseph Poirier <jdpoirier@gmail.com> wrote:

> On Sun, Mar 13, 2016 at 9:02 PM, AvSquirrel <notifications@github.com>
> wrote:
>
>> 336d17d
>> <https://github.com/cyoung/stratux/commit/336d17d615efd7f6e80f7e5752f78e354d84fcba>
>> seems to be working cleanly on my development branch (now 40+ commits ahead
>> of cyoung master). UI changes and physical disconnects / reconnects both
>> cause dump1090 to unload or reload as appropriate.
>>
>> One observation -- and I'd like you confirm that this is intentional --
>> is that any state changes (SDR enabled / disabled; SDR plugged in or
>> removed) cause both readers to be torn down, then set up again in the
>> desired configuration.
>>
> Yes, that's by design.
>

Doing it that way greatly simplifies the housekeeping. It's derived from
how rtl-sdr clients (e.g. http://gqrx.dk/) re/config, imperceptibly, on the
fly.

**Comment by jpoirier** [comment]
On Sun, Mar 13, 2016 at 9:02 PM, AvSquirrel <notifications@github.com>
wrote:

> 336d17d
> <https://github.com/cyoung/stratux/commit/336d17d615efd7f6e80f7e5752f78e354d84fcba>
> seems to be working cleanly on my development branch (now 40+ commits ahead
> of cyoung master). UI changes and physical disconnects / reconnects both
> cause dump1090 to unload or reload as appropriate.
>
btw, thanks for testing!

**Comment by AvSquirrel** [comment]
[This](https://github.com/jpoirier/stratux/blob/336d17d615efd7f6e80f7e5752f78e354d84fcba/main/sdr.go#L102-L115) is still blocking. It gets stuck on scanStderr.Scan() and eventually causes the 1090 reader to hang until the SDR is reset.

Can you split the stderr and stdout scans into separate goroutines?

**Comment by jpoirier** [comment]
On Mon, Mar 14, 2016 at 12:28 AM, AvSquirrel <notifications@github.com>
wrote:

> This
> <https://github.com/jpoirier/stratux/blob/336d17d615efd7f6e80f7e5752f78e354d84fcba/main/sdr.go#L102-L115>
> is still blocking. It gets stuck on scanStderr.Scan() and eventually causes
> the 1090 reader to hang until the SDR is reset.
>
Hmmm, ran it for nearly two days and didn't see that problem.

> Can you split the stderr and stdout scans into separate goroutines?
>
Yes. I'll do it now, and I think I'll ditch scan and go back to the
standard read method that was their previously.

**Comment by AvSquirrel** [comment]
FWIW, this is what I'm testing at the moment. Also got rid of the 1-second sleep, which was keeping dump1090 logs from properly filling.

````
	go func() {
		for {
			select {
			case <-done:
				return
			default:
				if scanStdout.Scan() {
					replayLog(scanStdout.Text(), MSGCLASS_DUMP1090)
				}
				if err := scanStdout.Err(); err != nil {
					log.Printf("scanStdout error: %s\n", err)
				}

				//if scanStderr.Scan() {
				//	replayLog(scanStderr.Text(), MSGCLASS_DUMP1090)
				//}
				//if err := scanStderr.Err(); err != nil {
				//	log.Printf("scanStderr error: %s\n", err)
				//}

				//time.Sleep(1 * time.Second)
			}
		}
	}()

	go func() {
		for {
			select {
			case <-done:
				return
			default:
				//if scanStdout.Scan() {
				//	replayLog(scanStdout.Text(), MSGCLASS_DUMP1090)
				//}
				//if err := scanStdout.Err(); err != nil {
				//	log.Printf("scanStdout error: %s\n", err)
				//}

				if scanStderr.Scan() {
					replayLog(scanStderr.Text(), MSGCLASS_DUMP1090)
				}
				if err := scanStderr.Err(); err != nil {
					log.Printf("scanStderr error: %s\n", err)
				}

				//time.Sleep(1 * time.Second)
			}
		}
	}()
````

**Comment by AvSquirrel** [comment]
https://github.com/AvSquirrel/stratux/commit/f7c9b7ec81d1422c06d6ea206b0591c96bfc453f

**Comment by jpoirier** [comment]
So was it blocking and requiring a reset or not?

**Comment by AvSquirrel** [comment]
> So was it blocking and requiring a reset or not?

Here's what I think happened:
- 336d17d blocked at L110 (`if scanStderr.Scan() {`) once dump1090 startup finished. During normal running, messages on stderr are few and far between, so the goroutine got to L110 and stopped.
- This kept sdr.go from reading stdout at L103 (it never iterated the loop)
- After about 100-200 traffic messages, the dump1090 stdout buffer filled, and blocked execution in dump1090 until it's emptied. This never happens due to the block on the stderr reads.
- Speed of reading stdout was exacerbated by the 1 second sleep.
- Resetting the SDR restarted dump1090, and allowed it to run for a little while until stdout filled again.

Since dump1090 is sending verbose traffic status (raw ES + decoded statistics) on stdout, the buffer fills relatively quickly. Ballpark estimate -- 8 lines * 40 bytes = 320 bytes per message, times 200 traffic messages = 64,000 bytes.  That would be consistent with a 2^16 byte named pipe buffer.

I ran with f7c9b7e overnight, no issues. It looks like you did something similar with 529b453, but adding buffering. I'll test this evening.

**Comment by jpoirier** [comment]
On Mon, Mar 14, 2016 at 8:44 AM, AvSquirrel <notifications@github.com>
wrote:

> So was it blocking and requiring a reset or not?
>
> Here's what I think happened:
>
>    - 336d17d
>    <https://github.com/cyoung/stratux/commit/336d17d615efd7f6e80f7e5752f78e354d84fcba>
>    blocked at L110 (if scanStderr.Scan() {) once dump1090 startup
>    finished. During normal running, messages on stderr are few and far
>    between, so the goroutine got to L110 and stopped.
>    - This kept sdr.go from reading stdout at L103 (it never iterated the
>    loop)
>    - After about 100-200 traffic messages, the dump1090 stdout buffer
>    filled, and blocked execution in dump1090 until it's emptied. This never
>    happens due to the block on the stderr reads.
>    - Speed of reading stdout was exacerbated by the 1 second sleep.
>    - Resetting the SDR restarted dump1090, and allowed it to run for a
>    little while until stdout filled again.
>
> Since dump1090 is sending verbose traffic status (raw ES + decoded
> statistics) on stdout, the buffer fills relatively quickly. Ballpark
> estimate -- 8 lines * 40 bytes = 320 bytes per message, times 200 traffic
> messages = 64,000 bytes. That would be consistent with a 2^16 byte named
> pipe buffer.
>
> I ran with f7c9b7e
> <https://github.com/cyoung/stratux/commit/f7c9b7ec81d1422c06d6ea206b0591c96bfc453f>
> overnight, no issues. It looks like you did something similar with 529b453
> <https://github.com/cyoung/stratux/commit/529b453ba2baa90969c8333d1b15ccee52add5dc>,
> but adding buffering. I'll test this evening.
>
Thanks for the info. Scan shouldn't/doesn't block so even if there were no
stderr messages it should have just continued to loop. I had concerns with
Scan handling stderr output tokens properly since stderr is unbuffered by
design but I didn't see any problems when I tested it. Regardless, it was
definitely my fuck-up for (mis)using Scan in that way in the first place.
:(

**Comment by jpoirier** [comment]
PR #334

**Pull request closed without merging**
